
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `ManualUser` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model ManualUser
 * 
 */
export type ManualUserModel = runtime.Types.Result.DefaultSelection<Prisma.$ManualUserPayload>

export type AggregateManualUser = {
  _count: ManualUserCountAggregateOutputType | null
  _avg: ManualUserAvgAggregateOutputType | null
  _sum: ManualUserSumAggregateOutputType | null
  _min: ManualUserMinAggregateOutputType | null
  _max: ManualUserMaxAggregateOutputType | null
}

export type ManualUserAvgAggregateOutputType = {
  id: number | null
}

export type ManualUserSumAggregateOutputType = {
  id: number | null
}

export type ManualUserMinAggregateOutputType = {
  id: number | null
  name: string | null
  email: string | null
}

export type ManualUserMaxAggregateOutputType = {
  id: number | null
  name: string | null
  email: string | null
}

export type ManualUserCountAggregateOutputType = {
  id: number
  name: number
  email: number
  _all: number
}


export type ManualUserAvgAggregateInputType = {
  id?: true
}

export type ManualUserSumAggregateInputType = {
  id?: true
}

export type ManualUserMinAggregateInputType = {
  id?: true
  name?: true
  email?: true
}

export type ManualUserMaxAggregateInputType = {
  id?: true
  name?: true
  email?: true
}

export type ManualUserCountAggregateInputType = {
  id?: true
  name?: true
  email?: true
  _all?: true
}

export type ManualUserAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ManualUser to aggregate.
   */
  where?: Prisma.ManualUserWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ManualUsers to fetch.
   */
  orderBy?: Prisma.ManualUserOrderByWithRelationInput | Prisma.ManualUserOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ManualUserWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ManualUsers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ManualUsers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned ManualUsers
  **/
  _count?: true | ManualUserCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: ManualUserAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: ManualUserSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ManualUserMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ManualUserMaxAggregateInputType
}

export type GetManualUserAggregateType<T extends ManualUserAggregateArgs> = {
      [P in keyof T & keyof AggregateManualUser]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateManualUser[P]>
    : Prisma.GetScalarType<T[P], AggregateManualUser[P]>
}




export type ManualUserGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ManualUserWhereInput
  orderBy?: Prisma.ManualUserOrderByWithAggregationInput | Prisma.ManualUserOrderByWithAggregationInput[]
  by: Prisma.ManualUserScalarFieldEnum[] | Prisma.ManualUserScalarFieldEnum
  having?: Prisma.ManualUserScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ManualUserCountAggregateInputType | true
  _avg?: ManualUserAvgAggregateInputType
  _sum?: ManualUserSumAggregateInputType
  _min?: ManualUserMinAggregateInputType
  _max?: ManualUserMaxAggregateInputType
}

export type ManualUserGroupByOutputType = {
  id: number
  name: string | null
  email: string
  _count: ManualUserCountAggregateOutputType | null
  _avg: ManualUserAvgAggregateOutputType | null
  _sum: ManualUserSumAggregateOutputType | null
  _min: ManualUserMinAggregateOutputType | null
  _max: ManualUserMaxAggregateOutputType | null
}

type GetManualUserGroupByPayload<T extends ManualUserGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ManualUserGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ManualUserGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ManualUserGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ManualUserGroupByOutputType[P]>
      }
    >
  >



export type ManualUserWhereInput = {
  AND?: Prisma.ManualUserWhereInput | Prisma.ManualUserWhereInput[]
  OR?: Prisma.ManualUserWhereInput[]
  NOT?: Prisma.ManualUserWhereInput | Prisma.ManualUserWhereInput[]
  id?: Prisma.IntFilter<"ManualUser"> | number
  name?: Prisma.StringNullableFilter<"ManualUser"> | string | null
  email?: Prisma.StringFilter<"ManualUser"> | string
  posts?: Prisma.PostListRelationFilter
}

export type ManualUserOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrderInput | Prisma.SortOrder
  email?: Prisma.SortOrder
  posts?: Prisma.PostOrderByRelationAggregateInput
}

export type ManualUserWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  email?: string
  AND?: Prisma.ManualUserWhereInput | Prisma.ManualUserWhereInput[]
  OR?: Prisma.ManualUserWhereInput[]
  NOT?: Prisma.ManualUserWhereInput | Prisma.ManualUserWhereInput[]
  name?: Prisma.StringNullableFilter<"ManualUser"> | string | null
  posts?: Prisma.PostListRelationFilter
}, "id" | "email">

export type ManualUserOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrderInput | Prisma.SortOrder
  email?: Prisma.SortOrder
  _count?: Prisma.ManualUserCountOrderByAggregateInput
  _avg?: Prisma.ManualUserAvgOrderByAggregateInput
  _max?: Prisma.ManualUserMaxOrderByAggregateInput
  _min?: Prisma.ManualUserMinOrderByAggregateInput
  _sum?: Prisma.ManualUserSumOrderByAggregateInput
}

export type ManualUserScalarWhereWithAggregatesInput = {
  AND?: Prisma.ManualUserScalarWhereWithAggregatesInput | Prisma.ManualUserScalarWhereWithAggregatesInput[]
  OR?: Prisma.ManualUserScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ManualUserScalarWhereWithAggregatesInput | Prisma.ManualUserScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"ManualUser"> | number
  name?: Prisma.StringNullableWithAggregatesFilter<"ManualUser"> | string | null
  email?: Prisma.StringWithAggregatesFilter<"ManualUser"> | string
}

export type ManualUserCreateInput = {
  name?: string | null
  email: string
  posts?: Prisma.PostCreateNestedManyWithoutUserInput
}

export type ManualUserUncheckedCreateInput = {
  id?: number
  name?: string | null
  email: string
  posts?: Prisma.PostUncheckedCreateNestedManyWithoutUserInput
}

export type ManualUserUpdateInput = {
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  email?: Prisma.StringFieldUpdateOperationsInput | string
  posts?: Prisma.PostUpdateManyWithoutUserNestedInput
}

export type ManualUserUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  email?: Prisma.StringFieldUpdateOperationsInput | string
  posts?: Prisma.PostUncheckedUpdateManyWithoutUserNestedInput
}

export type ManualUserCreateManyInput = {
  id?: number
  name?: string | null
  email: string
}

export type ManualUserUpdateManyMutationInput = {
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  email?: Prisma.StringFieldUpdateOperationsInput | string
}

export type ManualUserUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  email?: Prisma.StringFieldUpdateOperationsInput | string
}

export type ManualUserNullableScalarRelationFilter = {
  is?: Prisma.ManualUserWhereInput | null
  isNot?: Prisma.ManualUserWhereInput | null
}

export type ManualUserCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  email?: Prisma.SortOrder
}

export type ManualUserAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
}

export type ManualUserMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  email?: Prisma.SortOrder
}

export type ManualUserMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  email?: Prisma.SortOrder
}

export type ManualUserSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
}

export type ManualUserCreateNestedOneWithoutPostsInput = {
  create?: Prisma.XOR<Prisma.ManualUserCreateWithoutPostsInput, Prisma.ManualUserUncheckedCreateWithoutPostsInput>
  connectOrCreate?: Prisma.ManualUserCreateOrConnectWithoutPostsInput
  connect?: Prisma.ManualUserWhereUniqueInput
}

export type ManualUserUpdateOneWithoutPostsNestedInput = {
  create?: Prisma.XOR<Prisma.ManualUserCreateWithoutPostsInput, Prisma.ManualUserUncheckedCreateWithoutPostsInput>
  connectOrCreate?: Prisma.ManualUserCreateOrConnectWithoutPostsInput
  upsert?: Prisma.ManualUserUpsertWithoutPostsInput
  disconnect?: Prisma.ManualUserWhereInput | boolean
  delete?: Prisma.ManualUserWhereInput | boolean
  connect?: Prisma.ManualUserWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ManualUserUpdateToOneWithWhereWithoutPostsInput, Prisma.ManualUserUpdateWithoutPostsInput>, Prisma.ManualUserUncheckedUpdateWithoutPostsInput>
}

export type ManualUserCreateWithoutPostsInput = {
  name?: string | null
  email: string
}

export type ManualUserUncheckedCreateWithoutPostsInput = {
  id?: number
  name?: string | null
  email: string
}

export type ManualUserCreateOrConnectWithoutPostsInput = {
  where: Prisma.ManualUserWhereUniqueInput
  create: Prisma.XOR<Prisma.ManualUserCreateWithoutPostsInput, Prisma.ManualUserUncheckedCreateWithoutPostsInput>
}

export type ManualUserUpsertWithoutPostsInput = {
  update: Prisma.XOR<Prisma.ManualUserUpdateWithoutPostsInput, Prisma.ManualUserUncheckedUpdateWithoutPostsInput>
  create: Prisma.XOR<Prisma.ManualUserCreateWithoutPostsInput, Prisma.ManualUserUncheckedCreateWithoutPostsInput>
  where?: Prisma.ManualUserWhereInput
}

export type ManualUserUpdateToOneWithWhereWithoutPostsInput = {
  where?: Prisma.ManualUserWhereInput
  data: Prisma.XOR<Prisma.ManualUserUpdateWithoutPostsInput, Prisma.ManualUserUncheckedUpdateWithoutPostsInput>
}

export type ManualUserUpdateWithoutPostsInput = {
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  email?: Prisma.StringFieldUpdateOperationsInput | string
}

export type ManualUserUncheckedUpdateWithoutPostsInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  email?: Prisma.StringFieldUpdateOperationsInput | string
}


/**
 * Count Type ManualUserCountOutputType
 */

export type ManualUserCountOutputType = {
  posts: number
}

export type ManualUserCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  posts?: boolean | ManualUserCountOutputTypeCountPostsArgs
}

/**
 * ManualUserCountOutputType without action
 */
export type ManualUserCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ManualUserCountOutputType
   */
  select?: Prisma.ManualUserCountOutputTypeSelect<ExtArgs> | null
}

/**
 * ManualUserCountOutputType without action
 */
export type ManualUserCountOutputTypeCountPostsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.PostWhereInput
}


export type ManualUserSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  email?: boolean
  posts?: boolean | Prisma.ManualUser$postsArgs<ExtArgs>
  _count?: boolean | Prisma.ManualUserCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["manualUser"]>

export type ManualUserSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  email?: boolean
}, ExtArgs["result"]["manualUser"]>

export type ManualUserSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  email?: boolean
}, ExtArgs["result"]["manualUser"]>

export type ManualUserSelectScalar = {
  id?: boolean
  name?: boolean
  email?: boolean
}

export type ManualUserOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "name" | "email", ExtArgs["result"]["manualUser"]>
export type ManualUserInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  posts?: boolean | Prisma.ManualUser$postsArgs<ExtArgs>
  _count?: boolean | Prisma.ManualUserCountOutputTypeDefaultArgs<ExtArgs>
}
export type ManualUserIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type ManualUserIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $ManualUserPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "ManualUser"
  objects: {
    posts: Prisma.$PostPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    name: string | null
    email: string
  }, ExtArgs["result"]["manualUser"]>
  composites: {}
}

export type ManualUserGetPayload<S extends boolean | null | undefined | ManualUserDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ManualUserPayload, S>

export type ManualUserCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ManualUserFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ManualUserCountAggregateInputType | true
  }

export interface ManualUserDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['ManualUser'], meta: { name: 'ManualUser' } }
  /**
   * Find zero or one ManualUser that matches the filter.
   * @param {ManualUserFindUniqueArgs} args - Arguments to find a ManualUser
   * @example
   * // Get one ManualUser
   * const manualUser = await prisma.manualUser.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ManualUserFindUniqueArgs>(args: Prisma.SelectSubset<T, ManualUserFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ManualUserClient<runtime.Types.Result.GetResult<Prisma.$ManualUserPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one ManualUser that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ManualUserFindUniqueOrThrowArgs} args - Arguments to find a ManualUser
   * @example
   * // Get one ManualUser
   * const manualUser = await prisma.manualUser.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ManualUserFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ManualUserFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ManualUserClient<runtime.Types.Result.GetResult<Prisma.$ManualUserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ManualUser that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ManualUserFindFirstArgs} args - Arguments to find a ManualUser
   * @example
   * // Get one ManualUser
   * const manualUser = await prisma.manualUser.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ManualUserFindFirstArgs>(args?: Prisma.SelectSubset<T, ManualUserFindFirstArgs<ExtArgs>>): Prisma.Prisma__ManualUserClient<runtime.Types.Result.GetResult<Prisma.$ManualUserPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ManualUser that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ManualUserFindFirstOrThrowArgs} args - Arguments to find a ManualUser
   * @example
   * // Get one ManualUser
   * const manualUser = await prisma.manualUser.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ManualUserFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ManualUserFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ManualUserClient<runtime.Types.Result.GetResult<Prisma.$ManualUserPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more ManualUsers that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ManualUserFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all ManualUsers
   * const manualUsers = await prisma.manualUser.findMany()
   * 
   * // Get first 10 ManualUsers
   * const manualUsers = await prisma.manualUser.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const manualUserWithIdOnly = await prisma.manualUser.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends ManualUserFindManyArgs>(args?: Prisma.SelectSubset<T, ManualUserFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ManualUserPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a ManualUser.
   * @param {ManualUserCreateArgs} args - Arguments to create a ManualUser.
   * @example
   * // Create one ManualUser
   * const ManualUser = await prisma.manualUser.create({
   *   data: {
   *     // ... data to create a ManualUser
   *   }
   * })
   * 
   */
  create<T extends ManualUserCreateArgs>(args: Prisma.SelectSubset<T, ManualUserCreateArgs<ExtArgs>>): Prisma.Prisma__ManualUserClient<runtime.Types.Result.GetResult<Prisma.$ManualUserPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many ManualUsers.
   * @param {ManualUserCreateManyArgs} args - Arguments to create many ManualUsers.
   * @example
   * // Create many ManualUsers
   * const manualUser = await prisma.manualUser.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ManualUserCreateManyArgs>(args?: Prisma.SelectSubset<T, ManualUserCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many ManualUsers and returns the data saved in the database.
   * @param {ManualUserCreateManyAndReturnArgs} args - Arguments to create many ManualUsers.
   * @example
   * // Create many ManualUsers
   * const manualUser = await prisma.manualUser.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many ManualUsers and only return the `id`
   * const manualUserWithIdOnly = await prisma.manualUser.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends ManualUserCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ManualUserCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ManualUserPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a ManualUser.
   * @param {ManualUserDeleteArgs} args - Arguments to delete one ManualUser.
   * @example
   * // Delete one ManualUser
   * const ManualUser = await prisma.manualUser.delete({
   *   where: {
   *     // ... filter to delete one ManualUser
   *   }
   * })
   * 
   */
  delete<T extends ManualUserDeleteArgs>(args: Prisma.SelectSubset<T, ManualUserDeleteArgs<ExtArgs>>): Prisma.Prisma__ManualUserClient<runtime.Types.Result.GetResult<Prisma.$ManualUserPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one ManualUser.
   * @param {ManualUserUpdateArgs} args - Arguments to update one ManualUser.
   * @example
   * // Update one ManualUser
   * const manualUser = await prisma.manualUser.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ManualUserUpdateArgs>(args: Prisma.SelectSubset<T, ManualUserUpdateArgs<ExtArgs>>): Prisma.Prisma__ManualUserClient<runtime.Types.Result.GetResult<Prisma.$ManualUserPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more ManualUsers.
   * @param {ManualUserDeleteManyArgs} args - Arguments to filter ManualUsers to delete.
   * @example
   * // Delete a few ManualUsers
   * const { count } = await prisma.manualUser.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ManualUserDeleteManyArgs>(args?: Prisma.SelectSubset<T, ManualUserDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ManualUsers.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ManualUserUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many ManualUsers
   * const manualUser = await prisma.manualUser.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ManualUserUpdateManyArgs>(args: Prisma.SelectSubset<T, ManualUserUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ManualUsers and returns the data updated in the database.
   * @param {ManualUserUpdateManyAndReturnArgs} args - Arguments to update many ManualUsers.
   * @example
   * // Update many ManualUsers
   * const manualUser = await prisma.manualUser.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more ManualUsers and only return the `id`
   * const manualUserWithIdOnly = await prisma.manualUser.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends ManualUserUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ManualUserUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ManualUserPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one ManualUser.
   * @param {ManualUserUpsertArgs} args - Arguments to update or create a ManualUser.
   * @example
   * // Update or create a ManualUser
   * const manualUser = await prisma.manualUser.upsert({
   *   create: {
   *     // ... data to create a ManualUser
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the ManualUser we want to update
   *   }
   * })
   */
  upsert<T extends ManualUserUpsertArgs>(args: Prisma.SelectSubset<T, ManualUserUpsertArgs<ExtArgs>>): Prisma.Prisma__ManualUserClient<runtime.Types.Result.GetResult<Prisma.$ManualUserPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of ManualUsers.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ManualUserCountArgs} args - Arguments to filter ManualUsers to count.
   * @example
   * // Count the number of ManualUsers
   * const count = await prisma.manualUser.count({
   *   where: {
   *     // ... the filter for the ManualUsers we want to count
   *   }
   * })
  **/
  count<T extends ManualUserCountArgs>(
    args?: Prisma.Subset<T, ManualUserCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ManualUserCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a ManualUser.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ManualUserAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ManualUserAggregateArgs>(args: Prisma.Subset<T, ManualUserAggregateArgs>): Prisma.PrismaPromise<GetManualUserAggregateType<T>>

  /**
   * Group by ManualUser.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ManualUserGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ManualUserGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ManualUserGroupByArgs['orderBy'] }
      : { orderBy?: ManualUserGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ManualUserGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetManualUserGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the ManualUser model
 */
readonly fields: ManualUserFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for ManualUser.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ManualUserClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  posts<T extends Prisma.ManualUser$postsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ManualUser$postsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PostPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the ManualUser model
 */
export interface ManualUserFieldRefs {
  readonly id: Prisma.FieldRef<"ManualUser", 'Int'>
  readonly name: Prisma.FieldRef<"ManualUser", 'String'>
  readonly email: Prisma.FieldRef<"ManualUser", 'String'>
}
    

// Custom InputTypes
/**
 * ManualUser findUnique
 */
export type ManualUserFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ManualUser
   */
  select?: Prisma.ManualUserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ManualUser
   */
  omit?: Prisma.ManualUserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ManualUserInclude<ExtArgs> | null
  /**
   * Filter, which ManualUser to fetch.
   */
  where: Prisma.ManualUserWhereUniqueInput
}

/**
 * ManualUser findUniqueOrThrow
 */
export type ManualUserFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ManualUser
   */
  select?: Prisma.ManualUserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ManualUser
   */
  omit?: Prisma.ManualUserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ManualUserInclude<ExtArgs> | null
  /**
   * Filter, which ManualUser to fetch.
   */
  where: Prisma.ManualUserWhereUniqueInput
}

/**
 * ManualUser findFirst
 */
export type ManualUserFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ManualUser
   */
  select?: Prisma.ManualUserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ManualUser
   */
  omit?: Prisma.ManualUserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ManualUserInclude<ExtArgs> | null
  /**
   * Filter, which ManualUser to fetch.
   */
  where?: Prisma.ManualUserWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ManualUsers to fetch.
   */
  orderBy?: Prisma.ManualUserOrderByWithRelationInput | Prisma.ManualUserOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ManualUsers.
   */
  cursor?: Prisma.ManualUserWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ManualUsers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ManualUsers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ManualUsers.
   */
  distinct?: Prisma.ManualUserScalarFieldEnum | Prisma.ManualUserScalarFieldEnum[]
}

/**
 * ManualUser findFirstOrThrow
 */
export type ManualUserFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ManualUser
   */
  select?: Prisma.ManualUserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ManualUser
   */
  omit?: Prisma.ManualUserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ManualUserInclude<ExtArgs> | null
  /**
   * Filter, which ManualUser to fetch.
   */
  where?: Prisma.ManualUserWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ManualUsers to fetch.
   */
  orderBy?: Prisma.ManualUserOrderByWithRelationInput | Prisma.ManualUserOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ManualUsers.
   */
  cursor?: Prisma.ManualUserWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ManualUsers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ManualUsers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ManualUsers.
   */
  distinct?: Prisma.ManualUserScalarFieldEnum | Prisma.ManualUserScalarFieldEnum[]
}

/**
 * ManualUser findMany
 */
export type ManualUserFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ManualUser
   */
  select?: Prisma.ManualUserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ManualUser
   */
  omit?: Prisma.ManualUserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ManualUserInclude<ExtArgs> | null
  /**
   * Filter, which ManualUsers to fetch.
   */
  where?: Prisma.ManualUserWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ManualUsers to fetch.
   */
  orderBy?: Prisma.ManualUserOrderByWithRelationInput | Prisma.ManualUserOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing ManualUsers.
   */
  cursor?: Prisma.ManualUserWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ManualUsers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ManualUsers.
   */
  skip?: number
  distinct?: Prisma.ManualUserScalarFieldEnum | Prisma.ManualUserScalarFieldEnum[]
}

/**
 * ManualUser create
 */
export type ManualUserCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ManualUser
   */
  select?: Prisma.ManualUserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ManualUser
   */
  omit?: Prisma.ManualUserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ManualUserInclude<ExtArgs> | null
  /**
   * The data needed to create a ManualUser.
   */
  data: Prisma.XOR<Prisma.ManualUserCreateInput, Prisma.ManualUserUncheckedCreateInput>
}

/**
 * ManualUser createMany
 */
export type ManualUserCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many ManualUsers.
   */
  data: Prisma.ManualUserCreateManyInput | Prisma.ManualUserCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * ManualUser createManyAndReturn
 */
export type ManualUserCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ManualUser
   */
  select?: Prisma.ManualUserSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ManualUser
   */
  omit?: Prisma.ManualUserOmit<ExtArgs> | null
  /**
   * The data used to create many ManualUsers.
   */
  data: Prisma.ManualUserCreateManyInput | Prisma.ManualUserCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * ManualUser update
 */
export type ManualUserUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ManualUser
   */
  select?: Prisma.ManualUserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ManualUser
   */
  omit?: Prisma.ManualUserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ManualUserInclude<ExtArgs> | null
  /**
   * The data needed to update a ManualUser.
   */
  data: Prisma.XOR<Prisma.ManualUserUpdateInput, Prisma.ManualUserUncheckedUpdateInput>
  /**
   * Choose, which ManualUser to update.
   */
  where: Prisma.ManualUserWhereUniqueInput
}

/**
 * ManualUser updateMany
 */
export type ManualUserUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update ManualUsers.
   */
  data: Prisma.XOR<Prisma.ManualUserUpdateManyMutationInput, Prisma.ManualUserUncheckedUpdateManyInput>
  /**
   * Filter which ManualUsers to update
   */
  where?: Prisma.ManualUserWhereInput
  /**
   * Limit how many ManualUsers to update.
   */
  limit?: number
}

/**
 * ManualUser updateManyAndReturn
 */
export type ManualUserUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ManualUser
   */
  select?: Prisma.ManualUserSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ManualUser
   */
  omit?: Prisma.ManualUserOmit<ExtArgs> | null
  /**
   * The data used to update ManualUsers.
   */
  data: Prisma.XOR<Prisma.ManualUserUpdateManyMutationInput, Prisma.ManualUserUncheckedUpdateManyInput>
  /**
   * Filter which ManualUsers to update
   */
  where?: Prisma.ManualUserWhereInput
  /**
   * Limit how many ManualUsers to update.
   */
  limit?: number
}

/**
 * ManualUser upsert
 */
export type ManualUserUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ManualUser
   */
  select?: Prisma.ManualUserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ManualUser
   */
  omit?: Prisma.ManualUserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ManualUserInclude<ExtArgs> | null
  /**
   * The filter to search for the ManualUser to update in case it exists.
   */
  where: Prisma.ManualUserWhereUniqueInput
  /**
   * In case the ManualUser found by the `where` argument doesn't exist, create a new ManualUser with this data.
   */
  create: Prisma.XOR<Prisma.ManualUserCreateInput, Prisma.ManualUserUncheckedCreateInput>
  /**
   * In case the ManualUser was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ManualUserUpdateInput, Prisma.ManualUserUncheckedUpdateInput>
}

/**
 * ManualUser delete
 */
export type ManualUserDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ManualUser
   */
  select?: Prisma.ManualUserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ManualUser
   */
  omit?: Prisma.ManualUserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ManualUserInclude<ExtArgs> | null
  /**
   * Filter which ManualUser to delete.
   */
  where: Prisma.ManualUserWhereUniqueInput
}

/**
 * ManualUser deleteMany
 */
export type ManualUserDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ManualUsers to delete
   */
  where?: Prisma.ManualUserWhereInput
  /**
   * Limit how many ManualUsers to delete.
   */
  limit?: number
}

/**
 * ManualUser.posts
 */
export type ManualUser$postsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Post
   */
  select?: Prisma.PostSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Post
   */
  omit?: Prisma.PostOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PostInclude<ExtArgs> | null
  where?: Prisma.PostWhereInput
  orderBy?: Prisma.PostOrderByWithRelationInput | Prisma.PostOrderByWithRelationInput[]
  cursor?: Prisma.PostWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.PostScalarFieldEnum | Prisma.PostScalarFieldEnum[]
}

/**
 * ManualUser without action
 */
export type ManualUserDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ManualUser
   */
  select?: Prisma.ManualUserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ManualUser
   */
  omit?: Prisma.ManualUserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ManualUserInclude<ExtArgs> | null
}
