pull_request_rules:
  - name: Add Cleanup Label
    description: Adding cleanup label to temporary branches
    conditions:
      - -base ~= development/..
      - -base ~= staging/..
      - -head ~= staging/..
      - -head ~= development/..
    actions:
      label:
        remove:
          - cleanup
        toggle:
          - cleanup
  - name: delete head branch if "cleanup" label is present
    conditions:
      - merged
      - label = cleanup
    actions:
      delete_head_branch:
  - name: Adding automerge label
    description: Adding the automerge label for PRs  on main that do not have the
      conflicted label
    conditions:
      - label != conflicted
      - "#commits-behind<=10"
    actions:
      label:
        toggle:
          - automerge
  - name: Merging Staging-content with Main
    description: Automatically merging staging-contet with main
    conditions:
      - and:
          - or:
              - base = main
              - base ~= staging/..
          - label = automerge
          - label != conflicted
          - "#commits-behind <= 10"
          - "#commits-behind > 0"
    actions:
      update:
      comment:
        message: This  merge was automatically completed by mergify on behalf of @{{
          author }}.
      merge:
        method: merge
        commit_message_template: This commit was automatically completed by mergify on
          behalf of @{{ author }}
