pull_request_rules:
  - name: Label when a merge conflict occurs
    conditions:
      - conflict
    actions:
      label:
        toggle:
          - conflict

  - name: Labeling staging-content as an automerge branch
    conditions:
      - base = staging-content
      - target = main
    actions:
      label:
        toggle:
          - automerge
  
  - name: Automatic merge from staging-content to main when checks pass
    conditions:
      - "#conflict != true"
      - target = main
      - label = automerge
      - label != conflict
    actions:
      rebase:
      comment:
        message: Content for bravegrumpy.website was added by "@{{ author }}"
      merge:
        method: merge
