pull_request_rules:
  - name: Add Cleanup label
    description: Adding cleanup label if auto merge is present, and if it is not my
      perma-branches
    conditions:
      - label = automerge
      - -head ~= staging/..
      - -head ~= development/..
      - head != main
    actions:
      label:
        toggle:
          - cleanup
  - name: delete head branch if "cleanup" label is present
    conditions:
      - merged
      - label = cleanup
    actions:
      delete_head_branch:
  - name: Adding automerge label
    description: Adding the automerge label for PRs  on main that do not have the
      conflicted label
    conditions:
      - label != conflicted
      - "#commits-behind<=10"
    actions:
      label:
        toggle:
          - automerge
  - name: Merging Staging-content with Main
    description: Automatically merging staging-contet with main
    conditions:
      - and:
          - or:
              - base = main
              - base ~= staging/green
              - head ~= staging/..
          - label = automerge
          - label != conflicted
    actions:
      update:
      comment:
        message: Content for bravegrumpy.website  is added. This  merge was
          automatically completed by mergify.
      merge:
        method: merge
        commit_message_template: This commit was automatically completed by mergify on
          behalf of @{{ author }}