pull_request_rules:
  - name: Merging Staging-content with Main
    description: Automatically merging staging-contet with main
    conditions:
      - base = main
      - label = automerge
      - label != conflicted
      - "#commits-behind <= 5"
    actions:
      rebase:
      comment:
        message: Content for bravegrumpy.website  is added. This  merge was
          automatically completed by mergify.
      merge:
        method: merge
        commit_message_template: This commit was automatically completed by mergify on
          behalf of @{{ author }}
