name: bravegrumpy.website

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    ports: 
      - "3000:3000"
      - "5173:5173"
    command: ["npm", "run", "start"]
  
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3001:3000"
      - "5174:5173"
    command: >
      sh -c "npm run dev && --host"