version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: server
    ports:
      - "3000:3000"
    command: ["npm", "run", "start"]
  
  svelte:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: svelte
    ports:
      - "5173:5173"
    command: ["npm", "run", "dev"]