name: bravegrumpy.website
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    ports: 
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - HOST=backend
    command: ["npm", "run", "start"]
  
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "8000:8000"
    depends_on:
      - backend
    environment:
      - VITE_BACKEND_URL=http://backend:3000
    command: ["npm", "run", "dev"]